name:                stack-lib
version:             0.1.0.0
github:              "clintonmead/stack-lib"
license:             BSD3
author:              "Clinton Mead"
maintainer:          "clintonmead@gmail.com"
copyright:           "Copyright: (c) 2017 Clinton Mead"


# Metadata used when publishing your package
synopsis:            Wrapper to use stack as a library
category:            Development

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:
  Some wrapper functions around [stack](https://hackage.haskell.org/package/stack) intended to
  make it easier to use [stack](https://hackage.haskell.org/package/stack) as a library.

dependencies:
- base >= 4.7 && < 5
- stack
- path
- time
- monad-logger
- transformers

library:
  source-dirs: src
