name:                stack-lib
version:             0.1.0.0
github:              "clintonmead/stack-lib"
license:             BSD3
author:              "Clinton Mead"
maintainer:          "clintonmead@gmail.com"
copyright:           "Copyright: (c) 2017 Clinton Mead"
synopsis:            Wrapper to use stack as a library
category:            Development

description:
  Some wrapper functions around [stack](https://hackage.haskell.org/package/stack) intended to
  make it easier to use [stack](https://hackage.haskell.org/package/stack) as a library.

dependencies:
- base >= 4.7 && < 5
- stack
- path
- time
- monad-logger
- transformers

library:
  source-dirs: src
  ghc-options: -Wall
